// <auto-generated />
using System;
using DominioServicesLayer.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DominioServicesLayer.Migrations
{
    [DbContext(typeof(inventoriesContext))]
    [Migration("20190723033542_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DominioServicesLayer.Models.Empresa", b =>
                {
                    b.Property<int>("EmpId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("EmpLogo");

                    b.Property<string>("Empnombre")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("EmpId")
                        .HasName("PK__Empresa__AF2DBB99A0F137AB");

                    b.ToTable("Empresa");
                });

            modelBuilder.Entity("DominioServicesLayer.Models.Entrada", b =>
                {
                    b.Property<int>("EnId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("EnEstado")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("((1))");

                    b.Property<DateTime>("EnFecha")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("EnFechaModifica")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("EnFechaRegitro")
                        .HasColumnType("datetime");

                    b.Property<string>("EnObservacion")
                        .HasMaxLength(200);

                    b.Property<string>("EnProveedor")
                        .HasMaxLength(50);

                    b.Property<int?>("EnUsuarioCrea");

                    b.Property<int?>("EnUsuarioModifica");

                    b.HasKey("EnId")
                        .HasName("PK__Entrada__E3E8BE946EF52EB5");

                    b.HasIndex("EnUsuarioCrea");

                    b.HasIndex("EnUsuarioModifica");

                    b.ToTable("Entrada");
                });

            modelBuilder.Entity("DominioServicesLayer.Models.EntradaDetalle", b =>
                {
                    b.Property<int>("EnDetId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("EnDetCantidad")
                        .HasColumnType("decimal(25, 5)");

                    b.Property<decimal>("EnDetPrcIva")
                        .HasColumnName("EnDetPrcIVA")
                        .HasColumnType("decimal(25, 5)");

                    b.Property<int>("EnDetProuctoId");

                    b.Property<decimal>("EnDetVrIva")
                        .HasColumnName("EnDetVrIVA")
                        .HasColumnType("decimal(25, 5)");

                    b.Property<decimal>("EnDetVrTotal")
                        .HasColumnType("decimal(25, 5)");

                    b.Property<decimal>("EnDetVrUnit")
                        .HasColumnType("decimal(25, 5)");

                    b.Property<int>("EndDetEntradaId");

                    b.HasKey("EnDetId")
                        .HasName("PK__EntradaD__BF3CEE8DEF3010B2");

                    b.HasIndex("EnDetProuctoId");

                    b.HasIndex("EndDetEntradaId");

                    b.ToTable("EntradaDetalle");
                });

            modelBuilder.Entity("DominioServicesLayer.Models.Estado", b =>
                {
                    b.Property<int>("EstId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EstDescipcion")
                        .HasMaxLength(20);

                    b.HasKey("EstId")
                        .HasName("PK__Estado__665CAD5ECE111DCC");

                    b.ToTable("Estado");
                });

            modelBuilder.Entity("DominioServicesLayer.Models.Producto", b =>
                {
                    b.Property<int>("ProdId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ProdCategoria")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("ProdNombre")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<decimal?>("ProdPrecioCompra")
                        .HasColumnType("decimal(25, 4)");

                    b.Property<decimal?>("ProdPrecioVenta")
                        .HasColumnType("decimal(25, 4)");

                    b.Property<string>("ProdUm")
                        .IsRequired()
                        .HasColumnName("ProdUM")
                        .HasMaxLength(20);

                    b.HasKey("ProdId")
                        .HasName("PK__Producto__042785E54ADCD50E");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("DominioServicesLayer.Models.Usuario", b =>
                {
                    b.Property<int>("UsuId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool?>("UsuActivo")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("UsuClave")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<int?>("UsuIntentos")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("((0))");

                    b.Property<string>("UsuUsuario")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("UsuId")
                        .HasName("PK__Usuario__685263833772D33D");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("DominioServicesLayer.Models.UsuarioEmpresa", b =>
                {
                    b.Property<int>("UsuEmpid")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("UsuEmpEmpresa");

                    b.Property<int>("UsuEmpUsuario");

                    b.HasKey("UsuEmpid")
                        .HasName("PK__UsuarioE__0CDFECFF6718754D");

                    b.HasIndex("UsuEmpEmpresa");

                    b.HasIndex("UsuEmpUsuario");

                    b.ToTable("UsuarioEmpresa");
                });

            modelBuilder.Entity("DominioServicesLayer.Models.Entrada", b =>
                {
                    b.HasOne("DominioServicesLayer.Models.Usuario", "EnUsuarioCreaNavigation")
                        .WithMany("EntradaEnUsuarioCreaNavigation")
                        .HasForeignKey("EnUsuarioCrea")
                        .HasConstraintName("FK__Entrada__EnVrTot__628FA481");

                    b.HasOne("DominioServicesLayer.Models.Usuario", "EnUsuarioModificaNavigation")
                        .WithMany("EntradaEnUsuarioModificaNavigation")
                        .HasForeignKey("EnUsuarioModifica")
                        .HasConstraintName("FK__Entrada__EnUsuar__6383C8BA");
                });

            modelBuilder.Entity("DominioServicesLayer.Models.EntradaDetalle", b =>
                {
                    b.HasOne("DominioServicesLayer.Models.Producto", "EnDetProucto")
                        .WithMany("EntradaDetalle")
                        .HasForeignKey("EnDetProuctoId")
                        .HasConstraintName("FK__EntradaDe__EnDet__6754599E");

                    b.HasOne("DominioServicesLayer.Models.Entrada", "EndDetEntrada")
                        .WithMany("EntradaDetalle")
                        .HasForeignKey("EndDetEntradaId")
                        .HasConstraintName("FK__EntradaDe__EndDe__66603565");
                });

            modelBuilder.Entity("DominioServicesLayer.Models.UsuarioEmpresa", b =>
                {
                    b.HasOne("DominioServicesLayer.Models.Empresa", "UsuEmpEmpresaNavigation")
                        .WithMany("UsuarioEmpresa")
                        .HasForeignKey("UsuEmpEmpresa")
                        .HasConstraintName("FK__UsuarioEm__UsuEm__5CD6CB2B");

                    b.HasOne("DominioServicesLayer.Models.Usuario", "UsuEmpUsuarioNavigation")
                        .WithMany("UsuarioEmpresa")
                        .HasForeignKey("UsuEmpUsuario")
                        .HasConstraintName("FK__UsuarioEm__UsuEm__5BE2A6F2");
                });
#pragma warning restore 612, 618
        }
    }
}
